spring:
    application:
        name: DEFAULT-CONFIG

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
        fetchRegistry: true
        registerWithEureka: true
    instance:
        perfer-ip-address: true
